- README-security.adoc
- README-security.html
- finish/pom.xml
- finish/src/main/java/io/openliberty/guides/frontend/LoginBean.java
- finish/src/main/java/io/openliberty/guides/frontend/SessionUtils.java
- finish/src/main/java/io/openliberty/guides/frontend/liberty/config/server.xml
- finish/src/main/liberty/config/server.xml
- finish/src/main/webapp/error.xhtml
- finish/src/main/webapp/login.xhtml
- finish/src/test/java/it/io/openliberty/guides/rest/SecurityTest.java
Basic Security Application using FormAuthenticationMechanismDefinition annotation for the authentication. A basic user registry and RolesAllowed and DeclareRoles annotations for authorization. 
There is a rough draft of the README for the guide included and no tests are included yet.
> Basic Security Application

- finish/src/main/java/io/openliberty/guides/ui/HomeServlet.java
- finish/src/main/java/io/openliberty/guides/ui/UserBean.java
updated HomeServlet.java and UserBean.java
> Fix the indent in java files

- README.adoc
- finish/src/main/webapp/WEB-INF/web.xml
- Changed tags for web.xml
- UserBean.java not HomeServlet.java
> Updated readme

- README.adoc
- finish/src/main/java/io/openliberty/guides/ui/HomeServlet.java
- finish/src/main/liberty/config/server.xml
- finish/src/main/webapp/WEB-INF/web.xml
- finish/src/main/webapp/error403.html
- finish/src/test/java/it/io/openliberty/guides/security/SecurityTest.java
- finish/src/test/java/it/io/openliberty/guides/security/TestUtils.java
- start/src/main/liberty/config/server.xml
- start/src/main/webapp/WEB-INF/web.xml
- start/src/main/webapp/error403.html
- start/src/test/java/it/io/openliberty/guides/security/TestUtils.java
- updated the application to handle 403 error by redirecting to a html
- updated the Readme
- updated the tests
> Handle 403 error

- README.adoc
https://github.com/OpenLiberty/draft-guide-security-intro/issues/37
> Addressing Andrew's feedback

- finish/src/main/java/io/openliberty/guides/ui/HomeServlet.java
- finish/src/main/java/io/openliberty/guides/ui/UserBean.java
- finish/src/main/java/io/openliberty/guides/ui/Utils.java
- finish/src/test/java/it/io/openliberty/guides/security/SecurityTest.java
- finish/src/test/java/it/io/openliberty/guides/security/TestUtils.java
- start/src/main/java/io/openliberty/guides/ui/UserBean.java
- start/src/main/java/io/openliberty/guides/ui/Utils.java
- start/src/test/java/it/io/openliberty/guides/security/TestUtils.java
- added spaces
- made sure that no line longer than 88 characters
> fixed the java code format

- README.adoc
- finish/src/test/java/it/io/openliberty/guides/security/SecurityTest.java
_It also provides a SecurityContext API for programmatic security checks in Java EE containers._
_Java EE Security provides capability to configure the basic, form or custom form authentication mechanism by using annotations in the servlets. It also provides a SecurityContext API for programmatic security checks in Java EE containers. You’ll learn how to implement form authentication. Form authentication allows you to specify the web application login and error pages, assign the security constraint of a servlet and use the SecurityContext API to determine the role of a logged in user._
_The identity store is provided with the following user information credentials:_
_Now you can sign in to the HomeServlet with one of the credentials from the identity store._
_Within the <application-bnd> …
> Addressed YK's quick review feedback 

- README.adoc
- finish/src/main/liberty/config/server.xml
- finish/src/main/webapp/WEB-INF/web.xml
- finish/src/main/webapp/admin.xhtml
- finish/src/main/webapp/error.html
- finish/src/main/webapp/error403.html
- finish/src/main/webapp/user.xhtml
- finish/src/main/webapp/welcome.html
- finish/src/test/java/it/io/openliberty/guides/security/SecurityTest.java
- start/src/main/liberty/config/server.xml
- start/src/main/webapp/WEB-INF/web.xml
- start/src/main/webapp/admin.xhtml
- start/src/main/webapp/error.html
- start/src/main/webapp/error403.html
- start/src/main/webapp/user.xhtml
- start/src/main/webapp/welcome.html
- Revise README.adoc
- Misc fixes
> Revision and fixes

- README.adoc
- finish/src/main/webapp/WEB-INF/web.xml
Removed encoding password section
Added to web.xml to deny all other http methods to jsf urls
> Removing Encoding Password section

- README.adoc
Implemented feedback from: https://github.com/OpenLiberty/draft-guide-security-intro/issues/65
> Implemented feedback from ID review

- README.adoc
Addresses issue https://github.com/openliberty/guide-security-intro/issues/82
> added security tag

- finish/pom.xml
- start/pom.xml
RE: Issue https://github.com/OpenLiberty/guides-common/issues/268
> Fixed Dependencies

- README.adoc
- finish/pom.xml
- start/pom.xml
Reduce the SRVE9967W warnings from the messages.log
#86
> Merge qa to master: Updating Dependencies

- README.adoc
- finish/pom.xml
- finish/src/main/java/io/openliberty/guides/ui/HomeServlet.java
- finish/src/main/liberty/config/server.xml
- finish/src/main/liberty/config/userRegistry.xml
- finish/src/main/webapp/WEB-INF/web.xml
- finish/src/test/java/it/io/openliberty/guides/security/SecurityTest.java
- start/pom.xml
https://github.com/OpenLiberty/guides-common/issues/352
https://github.com/OpenLiberty/guides-common/issues/308
> hotspot & name convention update 

- .travis.yml
- README.adoc
- finish/pom.xml
- finish/src/main/java/io/openliberty/guides/ui/HomeServlet.java
- finish/src/main/liberty/config/server.xml
- finish/src/main/liberty/config/userRegistry.xml
- finish/src/main/webapp/WEB-INF/web.xml
- finish/src/test/java/it/io/openliberty/guides/security/SecurityTest.java
- start/pom.xml
> Merge qa to master: fix hotspots

- finish/pom.xml
- start/pom.xml
Re: https://github.com/OpenLiberty/guides-common/issues/419
> Updating dependencies in pom.xml

- README.adoc
- finish/pom.xml
- start/pom.xml
> Merge qa to master: update dependencies version

- finish/pom.xml
- start/pom.xml
- Specified the version at the plugin directly and removed corresponding property
- updated Jakarta.platform and org.eclipse.microprofile
> Tiago-updatePOM

- README.adoc
- finish/pom.xml
- start/pom.xml
> Merge qa to master: directly specify version in plugins

- finish/pom.xml
- finish/src/main/liberty/config/server.xml
- start/pom.xml
- start/src/main/liberty/config/server.xml
> Merge qa to master: specify app name directly in server.xml
